version: "3"
services: 
    client:
        build: ./client
        image: moaazzaki/jdc-client:latest
        stdin_open: true
        ports:
            - "3000:3000"
        networks: 
            - jdc-trial-network
    
    server:
        build: ./server
        image: moaazzaki/jdc-server:latest
        ports:
            - "3001:3001"
        networks: 
            - jdc-trial-network

networks: 
    jdc-trial-network:
        driver: bridge
    